CREATE TABLE siswa (
id INT(11) PRIMARY KEY AUTO_INCREMENT,
nis VARCHAR(20) NOT NULL,
nama_lengkap VARCHAR(100) NOT NULL,
jurusan VARCHAR(50),
alamat TEXT
);

CREATE TABLE matakuliah (
id INT(11) PRIMARY KEY AUTO_INCREMENT,
kode_mk VARCHAR(10) NOT NULL UNIQUE,
nama_mk VARCHAR(100) NOT NULL,
sks INT(2) NOT NULL,
dosen_pengampu VARCHAR(100)
);